kind: PersistentVolume
apiVersion: v1
metadata:
  name: frost-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/frost"
